name: KICS IaC scan

"on":
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  kics-iac-scan:
    uses: arnold-sa/gcp-security-workflows/.github/workflows/kics-iac-scan.yml@dev
    with:
      scan_path: "."
      results_bucket: project_trivy_1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      RESULTS_UPLOADER_SA: ${{ secrets.RESULTS_UPLOADER_SA }}
