name: Caller - Nmap network scan

"on":
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  nmap-network-scan:
    uses: arnold-sa/gcp-security-workflows/.github/workflows/nmap-network-scan.yml@dev
    with:
      targets: ${{ vars.SCAN_TARGET_CIDR }}
      results_bucket: project_trivy_1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      RESULTS_UPLOADER_SA: ${{ secrets.RESULTS_UPLOADER_SA }}
