name: security

on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  dev-scan:
    uses: arnold-sa/gcp-security-workflows/.github/workflows/dev-scan.yml@dev
    with:
      results_bucket: project_trivy_1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      RESULTS_UPLOADER_SA: ${{ secrets.RESULTS_UPLOADER_SA }}

  prowler-scan:
    if: github.ref == 'refs/heads/main'
    uses: arnold-sa/gcp-security-workflows/.github/workflows/deploy-scan.yml@dev
    with:
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      results_bucket: project_trivy_1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      PROWLER_SA: ${{ secrets.PROWLER_SA }}
      RESULTS_UPLOADER_SA: ${{ secrets.RESULTS_UPLOADER_SA }}